// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetcore_mvc_ecommerce.DataAccess.Data;

#nullable disable

namespace aspnetcore_mvc_ecommerce.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260324160504_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("aspnetcore_mvc_ecommerce.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Science & Technology"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Children's Books"
                        });
                });

            modelBuilder.Entity("aspnetcore_mvc_ecommerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Eleanor Voss",
                            CategoryId = 1,
                            Description = "A gripping tale of a young woman who discovers a hidden world beneath the streets of a crumbling city, where secrets of the past threaten to unravel everything she has ever known.",
                            ISBN = "9781234560001",
                            ImageUrl = "",
                            ListPrice = 29.0,
                            Price = 24.0,
                            Price100 = 17.0,
                            Price50 = 20.0,
                            Title = "The Crimson Horizon"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Marcus J. Aldren",
                            CategoryId = 2,
                            Description = "A fascinating journey through the rise of civilizations, exploring how culture, cooperation, and conflict shaped the modern world and what it truly means to be human.",
                            ISBN = "9781234560002",
                            ImageUrl = "",
                            ListPrice = 35.0,
                            Price = 30.0,
                            Price100 = 22.0,
                            Price50 = 26.0,
                            Title = "The Human Blueprint"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Dr. Lena Hartwell",
                            CategoryId = 3,
                            Description = "An accessible and mind-bending exploration of black holes, quantum mechanics, and the fabric of spacetime, written for curious minds who dare to question the nature of reality.",
                            ISBN = "9781234560003",
                            ImageUrl = "",
                            ListPrice = 40.0,
                            Price = 35.0,
                            Price100 = 25.0,
                            Price50 = 30.0,
                            Title = "Beyond the Event Horizon"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Sandra K. Mercer",
                            CategoryId = 4,
                            Description = "The untold story of a tech visionary who built an empire from a garage startup, transformed three industries, and redefined what it means to lead with obsession and purpose.",
                            ISBN = "9781234560004",
                            ImageUrl = "",
                            ListPrice = 45.0,
                            Price = 40.0,
                            Price100 = 30.0,
                            Price50 = 35.0,
                            Title = "Wired to Win"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Olivia Trent",
                            CategoryId = 5,
                            Description = "A magical adventure about a curious little fox named Ziggy who plants seeds among the stars and discovers that friendship and kindness make the whole universe bloom.",
                            ISBN = "9781234560005",
                            ImageUrl = "",
                            ListPrice = 20.0,
                            Price = 17.0,
                            Price100 = 12.0,
                            Price50 = 14.0,
                            Title = "Ziggy and the Star Garden"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Nathan Cross",
                            CategoryId = 1,
                            Description = "In a world where every thought is monitored and every word is logged, one programmer stumbles upon a forbidden algorithm that could either free humanity or destroy it forever.",
                            ISBN = "9781234560006",
                            ImageUrl = "",
                            ListPrice = 25.0,
                            Price = 21.0,
                            Price100 = 15.0,
                            Price50 = 18.0,
                            Title = "The Silent Protocol"
                        });
                });

            modelBuilder.Entity("aspnetcore_mvc_ecommerce.Models.Product", b =>
                {
                    b.HasOne("aspnetcore_mvc_ecommerce.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
