// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetcore_mvc_ecommerce.DataAccess.Data;

#nullable disable

namespace aspnetcore_mvc_ecommerce.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260323023524_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("aspnetcore_mvc_ecommerce.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Science & Technology"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Children's Books"
                        });
                });

            modelBuilder.Entity("aspnetcore_mvc_ecommerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            CategoryId = 1,
                            Description = "A story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, set in the Jazz Age on Long Island.",
                            ISBN = "9780743273565",
                            ListPrice = 29.0,
                            Price = 24.0,
                            Price100 = 17.0,
                            Price50 = 20.0,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Yuval Noah Harari",
                            CategoryId = 2,
                            Description = "A brief history of humankind, exploring how Homo sapiens came to dominate the Earth and what the future holds for our species.",
                            ISBN = "9780062316097",
                            ListPrice = 35.0,
                            Price = 30.0,
                            Price100 = 22.0,
                            Price50 = 26.0,
                            Title = "Sapiens"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Stephen Hawking",
                            CategoryId = 3,
                            Description = "An exploration of cosmology, black holes, and the nature of time written for general audiences by one of the greatest physicists.",
                            ISBN = "9780553380163",
                            ListPrice = 40.0,
                            Price = 35.0,
                            Price100 = 25.0,
                            Price50 = 30.0,
                            Title = "A Brief History of Time"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Walter Isaacson",
                            CategoryId = 4,
                            Description = "The exclusive biography of Steve Jobs, based on more than forty interviews with Jobs conducted over two years.",
                            ISBN = "9781451648539",
                            ListPrice = 45.0,
                            Price = 40.0,
                            Price100 = 30.0,
                            Price50 = 35.0,
                            Title = "Steve Jobs"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Antoine de Saint-Exupéry",
                            CategoryId = 5,
                            Description = "A poetic tale about a young prince who travels the universe and learns about life, love, and loss.",
                            ISBN = "9780156012195",
                            ListPrice = 20.0,
                            Price = 17.0,
                            Price100 = 12.0,
                            Price50 = 14.0,
                            Title = "The Little Prince"
                        },
                        new
                        {
                            Id = 6,
                            Author = "George Orwell",
                            CategoryId = 5,
                            Description = "A dystopian novel set in a totalitarian society where Big Brother watches your every move and independent thinking is a crime.",
                            ISBN = "9780451524935",
                            ListPrice = 25.0,
                            Price = 21.0,
                            Price100 = 15.0,
                            Price50 = 18.0,
                            Title = "1984"
                        });
                });

            modelBuilder.Entity("aspnetcore_mvc_ecommerce.Models.Product", b =>
                {
                    b.HasOne("aspnetcore_mvc_ecommerce.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
